version: '3.8'

services:
  jenkins:
    container_name: jenkins
    restart: always
    build: .
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
  agent:
    container_name: agent
    image: jenkins/ssh-agent:latest-jdk11
    privileged: true
    user: root
    expose:
      - 22
    environment:
      # Aqui pueden crear un .env en donde pasarán su clave pública del jenkins-agent (generada en la máquina anfitriona) o pueden pasarla directamente (sin comillas)
      JENKINS_AGENT_SSH_PUBKEY: ${SSH_PUB_KEY} 

volumes:
  jenkins_home:
    driver: local
